name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validation
      run: |
        # Add your validation command
        az login
        az  deployment group validate --resource-group challa003 --template-file total.json
    - name: Deploy
      run: |
        # Add your deployment command   
         az deployment group create --resource-group challa003 --template-file total.json
